nameOverride: 'agent-server'
fullnameOverride: 'agent-server'
replicaCount: 1
app:
  name: 'agent-server'
application:
  api:
    name: agent-server
    imagePullPolicy: IfNotPresent
    image:
      repository: registry.cloudscript.com.br/agentscript/agent-server
      tag: "v0.0.24"
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 200m
        memory: 256Mi
    env:
      - name: ENV
        value: 'production'
      - name: DB_CONNECTION_STRING
        value: postgres://agentscript:19d7G0b94_2d35@postgresql:5432/agent_script?connect_timeout=10&sslmode=disable
      - name: ADMIN_TOKEN
        value: YDyhdu3n32kjbGF7nh98asdSDfsad322
    probes:
      enabled: true
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 60
    ports:
      - name: api-port
        containerPort: 8080
        protocol: TCP
image:
  pullPolicy: Always
imagePullSecrets:
  - name: gitlab-registry
secret:
  enabled: false
  secretName: agent-server-secrets-production
serviceAccount:
  create: true
services:
  - name: agent-server
    enabled: true
    port: 8080
    ingress:
      enabled: true
      className: 'nginx'
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      host: agent-server.opsscript.io
      paths:
        - path: /
          pathType: Prefix
      tls:
        secretName: agent-server-tls-secret
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
nodeSelector:
  node-group: system
