project_name: agent-server

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: "agent-server"
    env:
      - CGO_ENABLED=0
      - GOPRIVATE='gitlab.cloudscript.com.br/general/*,gitlab.cloudscript.com.br/opsscript/*,gitlab.cloudscript.com.br/agentscript/*'
    targets:
      - linux_amd64
    main: ./cmd/
    binary: agent-server
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -extldflags '-static'
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commitSHA={{.FullCommit}}
      - -X main.buildDate={{.Date}}

gitlab_urls:
  api: https://gitlab.cloudscript.com.br/api/v4/
  download: https://gitlab.cloudscript.com.br
  skip_tls_verify: true
  use_package_registry: true
  use_job_token: true
  
release:
  gitlab:
    owner: ""
    name: "31" #Gitlab project ID
  disable: false

# This is a model with Dockerfile.goreleaser
dockers:
  - image_templates: [ "registry.cloudscript.com.br/agentscript/agent-server:{{ .Tag }}" ]
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    extra_files:
      - database
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://gitlab.cloudscript.com.br/agentscript/agent-server
      - --label=org.opencontainers.image.source=https://gitlab.cloudscript.com.br/agentscript/agent-server
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=BSL

nfpms:
  - maintainer: DevOps Team <devops@cloudscript.com.br>
    description: AgentScript Integration App.
    homepage: https://gitlab.cloudscript.com.br/agentscript/agent-server
    license: BSL