{{- range .Values.services }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" $ }}"
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" $ | nindent 4 }}
---
{{- end }}
{{- end }}
